server:
    port: 8003

# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   测试环境：java -jar quartz-feign.jar --spring.profiles.active=test
#   生产环境：java -jar quartz-feign.jar --spring.profiles.active=prod
spring: 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://localhost:3306/mysql?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: james
  
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: com.quartz.job.special.MyStdJDBCDelegate #org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
      
mybatis-plus:
  mapper-locations: classpath*:/mapper.contractclone/**Mapper.xml    #把xml文件放在com.XX.mapper.contractclone.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  typeAliasesPackage: com.quartz.domain         #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  file: quartz-feign.log
  level:
    com.quartz: debug     
    